- id: "1548594082873"
  alias: Update Available Notifications
  trigger:
    - entity_id: updater.updater
      platform: state
  condition: []
  action:
    - data:
        message: Update for Home Assistant is available.
      service: notify.mobile_app_kim_alster_glimberg
    - data:
        message: Update for Home Assistant is available.
      service: notify.gmail
- alias: Change state to Home when Alarm is disarmed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.skumparp_alarm
      from: armed_away
      to: disarmed
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_status
        option: Home
  id: 5dc21f7b3008473bb014147eb9c4c2fe
- alias: Change state to Away when Alarm is armed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.skumparp_alarm
      from: disarmed
      to: armed_away
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_status
        option: Away
  id: da1d4c57d6744f95bbf9148421ba61b4
- id: 7a51e31823014c0da831599eb662af08
  alias: Turn off lights in kids room when coming home late
  trigger:
    - entity_id: input_select.home_status
      platform: state
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: Home
        - after: "19:30:00"
          condition: time
  action:
    - entity_id: group.fonster_lampor_barn_rum
      service: homeassistant.turn_off
    - data: {}
      entity_id: light.skyfacing_zha_group_0x0004
      service: homeassistant.turn_off
  mode: single
- alias: Turn off lights in bedroom when coming home late
  trigger:
    - platform: state
      entity_id: input_select.home_status
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.home_status
        state: Home
      - condition: time
        after: "21:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id: group.fonster_lampor_sovrum
  id: 58f6acdc48cc4110bcbf9bef28f34bff
- alias: Turn on game and tv in Sams room when home and when between 9am and 8pm.
  trigger:
    - platform: state
      entity_id: input_select.home_status
    - platform: time
      at: 09:00:00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.home_status
        state: Home
      - condition: time
        before: "19:30:00"
      - condition: time
        after: 08:59:00
  action:
    - service: homeassistant.turn_on
      entity_id: switch.sovrum_sam_tv_nexa_4
  id: 96450b1e953d4b248893abafbd308bf4
- alias:
    Turn off game and tv in Sams room when not home and when between 8pm and
    9am.
  trigger:
    - platform: state
      entity_id: input_select.home_status
    - platform: time
      at: "19:30:00"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.home_status
        state: Away
      - condition: and
        conditions:
          - condition: time
            after: "19:29:00"
          - condition: time
            before: 09:00:00
  action:
    - service: homeassistant.turn_off
      entity_id: switch.sovrum_sam_tv_nexa_4
  id: a630bbb6ad27456da3f26f01c62c6cee
- id: ae163c926136455dab10ccb2a479d21d
  alias: Turn off all lights if it is very late and the lights are still on
  trigger:
    - at: 01:00:00
      platform: time
  condition:
    - condition: state
      entity_id: group.all_fonster_lampor
      state: "on"
  action:
    - entity_id: group.all_fonster_lampor
      service: homeassistant.turn_off
    - entity_id: input_boolean.morning_mode
      service: input_boolean.turn_off
    - data: {}
      entity_id: light.all_skyfacing_zha_group_0x0005
      service: homeassistant.turn_off
    - data:
        message: Found some lights still on at 01:00 AM. Turning them off now...
      service: notify.mobile_app_kim_alster_glimberg
  mode: single
- id: 90e4b8a6d24f4e7895b2024d813fa370
  alias: Turn on lights at sunset
  trigger:
    - event: sunset
      offset: -00:45:00
      platform: sun
  condition:
    - condition: or
      conditions:
        - before: "19:30:00"
          condition: time
        - condition: state
          entity_id: input_select.home_status
          state: Away
  action:
    - entity_id: group.all_fonster_lampor
      service: homeassistant.turn_on
    - data: {}
      entity_id: light.parking_zha_group_0x0001
      service: homeassistant.turn_on
    - data: {}
      entity_id: light.front_door_zha_group_0x0002
      service: homeassistant.turn_on
    - data: {}
      entity_id: light.garden_zha_group_0x0006
      service: homeassistant.turn_on
    - entity_id: group.ute_belysning
      service: homeassistant.turn_on
  mode: single
- id: 367e8e9bcb0243b1b09bfeb44cb115e9
  alias: Turn off lights at sunsrise
  trigger:
    - event: sunrise
      offset: 00:45:00
      platform: sun
  action:
    - entity_id: group.all_fonster_lampor
      service: homeassistant.turn_off
    - entity_id: group.ute_belysning
      service: homeassistant.turn_off
    - data:
        cluster_id: 6
        command: 0
        group: 1
      service: zha.issue_zigbee_group_command
    - data:
        cluster_id: 6
        command: 0
        group: 2
      service: zha.issue_zigbee_group_command
    - data:
        cluster_id: 6
        command: 0
        group: 6
      service: zha.issue_zigbee_group_command
- id: cb67ff6e29444b1cafd6b35dc148b42a
  alias: Turn off lights in Kids room if home
  trigger:
    - at: "19:30:00"
      platform: time
  condition:
    - condition: state
      entity_id: input_select.home_status
      state: Home
  action:
    - entity_id: group.fonster_lampor_barn_rum
      service: homeassistant.turn_off
    - data: {}
      entity_id: light.skyfacing_zha_group_0x0004
      service: homeassistant.turn_off
  mode: single
- alias: Turn off lights in bedroom if home
  trigger:
    - platform: time
      at: "21:00:00"
  condition:
    condition: state
    entity_id: input_select.home_status
    state: Home
  action:
    - service: homeassistant.turn_off
      entity_id: group.fonster_lampor_sovrum
  id: 25c78f6df30f4ccaadf90a5a38c113a8
- alias: Turn on bedroom lights in the morning if before sunrise
  trigger:
    - platform: time
      at: 06:45:00
    - platform: state
      entity_id: input_boolean.morning_mode
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
  action:
    - service: homeassistant.turn_on
      entity_id: group.fonster_lampor_barn_rum
    - service: homeassistant.turn_on
      entity_id: group.fonster_lampor_sovrum
  id: 31d8157fa2424e7d9b7b1a029ae6e8e0
- id: 0c912f631cb54be18390f9886f3dc0d1
  alias: Turn on lights in the morning if before sunrise
  trigger:
    - at: 06:30:00
      platform: time
  condition:
    - condition: and
      conditions:
        - before: sunrise
          condition: sun
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "on"
  action:
    - entity_id: group.fonster_lampor
      service: homeassistant.turn_on
    - data:
        cluster_id: 6
        command: 1
        group: 1
      service: zha.issue_zigbee_group_command
    - data:
        cluster_id: 6
        command: 1
        group: 2
      service: zha.issue_zigbee_group_command
    - data:
        cluster_id: 6
        command: 1
        group: 6
      service: zha.issue_zigbee_group_command
- id: "1563627826205"
  alias: Shut Down Octopi when Print Complete
  trigger:
    - entity_id: sensor.octoprint_job_percentage
      platform: state
      to: "100.0"
  condition: []
  action:
    - service: script.shutdown_octoprint
- id: "1580318781531"
  alias: Notify me when the lights become unavailable
  description: Notify me when the lights become unavailable
  trigger:
    - platform: template
      value_template:
        "{{ states.light | selectattr('state', 'in', ['unavailable', 'unknown',\
        \ 'none']) \n                | list\n                | length > 0  }}\n"
  condition: []
  action:
    - data_template:
        message:
          "Unavailable light detected: \n {{ states.light | selectattr('state',\
          \ 'in', ['unavailable', 'unknown', 'none'])\n                 | map(attribute='name')\
          \ \n                 | list \n                 | join('\\n')}}\n"
      service: notify.mobile_app_kim_alster_glimberg
- id: "1585489737608"
  alias: Receive Blue Connect Meassurements
  description: Receive data from Blue Connect via IFTTT webhook
  trigger:
    - platform: webhook
      webhook_id: !secret blueconnect_webhook_id
  condition: []
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.pool_temperature
        value: "{{trigger.json.temperature | float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.pool_ph
        value: "{{trigger.json.ph | float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.pool_orp
        value: "{{trigger.json.orp | float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.pool_salinity
        value: "{{trigger.json.salinity | float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.pool_conductivity
        value: "{{trigger.json.conductivity | float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.pool_analyzed_at
        value:
          '{{as_timestamp(strptime(trigger.json.analyzedAt,"%B %d, %Y at %I:%M%p"))
          | float}}'
    - service: input_number.set_value
      data_template:
        entity_id: input_number.blue_connect_time_delay
        value:
          '{{(as_timestamp(utcnow()) - as_timestamp(strptime(trigger.json.analyzedAt,"%B
          %d, %Y at %I:%M%p")))/60| int}}'
- id: "1587933664663"
  alias: Turn on window lights at sunset
  description: ""
  trigger:
    - event: sunset
      offset: -00:45:00
      platform: sun
  condition: []
  action:
    - data: {}
      entity_id: light.parking_zha_group_0x0001
      service: homeassistant.turn_on
    - data: {}
      entity_id: light.front_door_zha_group_0x0002
      service: homeassistant.turn_on
    - data: {}
      entity_id: light.garden_zha_group_0x0006
      service: homeassistant.turn_on
    - data: {}
      entity_id: switch.nedre_belysning
      service: homeassistant.turn_on
    - brightness_pct: 43
      device_id: 3a0ef9aaf6834e0aaf02d39b08256b21
      domain: light
      entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ws_opal_980lm_e16c15fe_level_light_color_on_off
      type: turn_on
    - brightness_pct: 50
      device_id: bd5d8edfde5248c681cfb41edbaeb8a0
      domain: light
      entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_806lm_d54435fe_level_on_off
      type: turn_on
    - brightness_pct: 43
      device_id: f7ed1b67e0bf4a07b718da9bd85fbc7b
      domain: light
      entity_id: light.ikea_of_sweden_tradfri_bulb_e14_ws_470lm_5b2f9ffe_level_light_color_on_off
      type: turn_on
  mode: single
- id: "1585489737608wwww"
  alias: Receive successful build
  description: Receive successful build from Github Actions
  trigger:
    platform: webhook
    webhook_id: !secret github_web_hook_id
  action:
    - service: hassio.addon_restart
      data:
        addon: core_git_pull
    - delay: 0:02
    - service: homeassistant.restart
- id: "1585489737608cxxx"
  alias: Config changed listener
  description: Watching for changed files in config folder
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: deleted
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: moved
  action:
    - service: shell_command.debug
    - service: shell_command.commit_config
