homeassistant:
  # Name of the location where Home Assistant is running
  name: Skumparp
  # Location required to calculate the time the sun rises and sets
  latitude: 55.5398837
  longitude: 12.9652643
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

#logger:
#  default: info

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.date
      - sensor.yr_symbol

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

google_assistant:
  project_id: hassio-186ad
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  agent_user_id: !secret ga_agent_id
  api_key: !secret ga_api_key
  exposed_domains:
    - switch
    - light
    - group

# Notification
notify: !include service/notify.yaml

# Verisure
verisure: !include verisure.yaml

# Mercedes
mercedesme:
  username: !secret mercedesme_username
  password: !secret mercedesme_password
  
# RFXtrx
rfxtrx: !include rfxtrx.yaml

# Entities
switch: !include_dir_merge_list switch

sensor: !include_dir_merge_list sensor

input_select: !include misc/input_select.yaml

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml
