homeassistant:
  # Name of the location where Home Assistant is running
  name: Skumparp
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  external_url: !secret external_url
  internal_url: !secret internal_url
  allowlist_external_dirs:
    - /config
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp
# https://www.home-assistant.io/integrations/default_config
default_config:

#https://www.home-assistant.io/integrations/my/ prereqs for HACS
my:

http:
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  login_attempts_threshold: 5
  # Add use_x_forwarded_for
  use_x_forwarded_for: true
  # Add the Cloudflare IPs as trusted proxies https://www.cloudflare.com/ips-v4
  trusted_proxies:
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

#logger:
#  default: error
#  logs:
#    homeassistant.components.zha: debug
#    zigpy_deconz.zigbee: debug
#    zigpy_deconz: debug

# Text to speech
tts:
  - platform: google_translate

stream:

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret gmail_username
  tfa_password: !secret gmail_app_password
# Octopi Shutdown
#rest_command:
#  shut_down_octoprint:
#    url: !secret octopi_shutdown_url
#    method: POST
#    headers:
#      X-Api-Key: !secret octopi_api_key

camera:
  - platform: aarlo
#  - platform: mjpeg
#    name: OctoPrint
#    still_image_url: !secret octopi_still_image_url
#    mjpeg_url: !secret octopi_mjpeg_url

# Google Assistant
# google_assistant: !include service/google_assistant.yaml

# Google Calendars
#google:
#  client_id: !secret google_calendar_client_id
#  client_secret: !secret google_calendar_client_secret

# Notification
notify: !include service/notify.yaml

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
automation secret: !include secret_automations.yaml
script: !include scripts.yaml

# Entities
binary_sensor:
  - platform: workday
    country: DK
    workdays: [mon, tue, wed, thu, fri]
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - connectivity

# switch: !include_dir_merge_list switch

sensor: !include_dir_merge_list sensor

input_select: !include misc/input_select.yaml
input_number: !include misc/input_number.yaml
input_boolean: !include misc/input_boolean.yaml

folder_watcher:
  - folder: /config
    patterns:
      - 'lovelace*'
      - '*.yaml'

shell_command:
  commit_config: /config/comitter.sh
