Last login: Thu Jul 18 21:38:13 on ttys001
kimalstrsensair:~ kimalster$ ssh -i /Users/kimalster/.ssh/hassio_rsa -p 22222 root@hassio.local
root@hassio:~# cd /resin-data/homeassistant
root@hassio:/resin-data/homeassistant# ls
README.md	    groups.yaml		  misc		service
automations.yaml    home-assistant.log	  rfxtrx.yaml	switch
configuration.yaml  home-assistant_v2.db  scripts.yaml	tts
customize.yaml	    homebridge		  secrets.yaml	verisure.yaml
deps		    known_devices.yaml	  sensor	zigbee.db
root@hassio:/resin-data/homeassistant# git diff
-sh: git: command not found
root@hassio:/resin-data/homeassistant# cat automations.yaml 
- id: '1548594082873'
  alias: Update Available Notifications
  trigger:
  - entity_id: updater.updater
    platform: state
  condition: []
  action:
  - data:
      message: Update for Home Assistant is available.
    service: notify.ios_kim_alster_glimberg
  - data:
      message: Update for Home Assistant is available.
    service: notify.gmail
- alias: Change state to Home when Alarm is disarmed
  trigger:
  - platform: state
    entity_id: alarm_control_panel.skumparp_alarm
    from: armed_away
    to: disarmed
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.home_status
      option: Home
  id: 5dc21f7b3008473bb014147eb9c4c2fe
- alias: Change state to Away when Alarm is armed
  trigger:
  - platform: state
    entity_id: alarm_control_panel.skumparp_alarm
    from: disarmed
    to: armed_away
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.home_status
      option: Away
  id: da1d4c57d6744f95bbf9148421ba61b4
- alias: Turn off lights in kids room when coming home late
  trigger:
  - platform: state
    entity_id: input_select.home_status
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.home_status
      state: Home
    - condition: time
      after: '19:30:00'
  action:
  - service: homeassistant.turn_off
    entity_id: group.fonster_lampor_barn_rum
  id: 7a51e31823014c0da831599eb662af08
- alias: Turn off lights in bedroom when coming home late
  trigger:
  - platform: state
    entity_id: input_select.home_status
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.home_status
      state: Home
    - condition: time
      after: '21:00:00'
  action:
  - service: homeassistant.turn_off
    entity_id: group.fonster_lampor_sovrum
  id: 58f6acdc48cc4110bcbf9bef28f34bff
- alias: Turn on game and tv in Sams room when home and when between 9am and 8pm.
  trigger:
  - platform: state
    entity_id: input_select.home_status
  - platform: time
    at: 09:00:00
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.home_status
      state: Home
    - condition: time
      before: '19:30:00'
    - condition: time
      after: 08:59:00
  action:
  - service: homeassistant.turn_on
    entity_id: switch.sovrum_sam_tv_nexa_4
  id: 96450b1e953d4b248893abafbd308bf4
- alias: Turn off game and tv in Sams room when not home and when between 8pm and
    9am.
  trigger:
  - platform: state
    entity_id: input_select.home_status
  - platform: time
    at: '19:30:00'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.home_status
      state: Away
    - condition: and
      conditions:
      - condition: time
        after: '19:29:00'
      - condition: time
        before: 09:00:00
  action:
  - service: homeassistant.turn_off
    entity_id: switch.sovrum_sam_tv_nexa_4
  id: a630bbb6ad27456da3f26f01c62c6cee
- alias: Turn off all lights if it is very late and the lights are still on
  trigger:
  - platform: time
    at: 01:00:00
  condition:
    condition: state
    entity_id: group.all_fonster_lampor
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_fonster_lampor
  - service: input_boolean.turn_off
    entity_id: input_boolean.morning_mode
  - service: notify.ios_kim_alster_glimberg
    data:
      message: Found some lights still on at 01:00 AM. Turning them off now...
  id: ae163c926136455dab10ccb2a479d21d
- alias: Turn on lights at sunset
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
    condition: or
    conditions:
    - condition: time
      before: '19:30:00'
    - condition: state
      entity_id: input_select.home_status
      state: Away
  action:
  - service: homeassistant.turn_on
    entity_id: group.all_fonster_lampor
  - service: homeassistant.turn_on
    entity_id: group.ute_belysning
  id: 90e4b8a6d24f4e7895b2024d813fa370
- alias: Turn off lights at sunsrise
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:45:00
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_fonster_lampor
  - service: homeassistant.turn_off
    entity_id: group.ute_belysning
  id: 367e8e9bcb0243b1b09bfeb44cb115e9
- alias: Turn off lights in Kids room if home
  trigger:
  - platform: time
    at: '19:30:00'
  condition:
    condition: state
    entity_id: input_select.home_status
    state: Home
  action:
  - service: homeassistant.turn_off
    entity_id: group.fonster_lampor_barn_rum
  id: cb67ff6e29444b1cafd6b35dc148b42a
- alias: Turn off lights in bedroom if home
  trigger:
  - platform: time
    at: '21:00:00'
  condition:
    condition: state
    entity_id: input_select.home_status
    state: Home
  action:
  - service: homeassistant.turn_off
    entity_id: group.fonster_lampor_sovrum
  id: 25c78f6df30f4ccaadf90a5a38c113a8
- alias: Turn on bedroom lights in the morning if before sunrise
  trigger:
  - platform: time
    at: 06:45:00
  - platform: state
    entity_id: input_boolean.morning_mode
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: group.fonster_lampor_barn_rum
  - service: homeassistant.turn_on
    entity_id: group.fonster_lampor_sovrum
  id: 31d8157fa2424e7d9b7b1a029ae6e8e0
- alias: Turn on lights in the morning if before sunrise
  trigger:
  - platform: time
    at: 06:30:00
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: group.fonster_lampor
  id: 0c912f631cb54be18390f9886f3dc0d1
root@hassio:/resin-data/homeassistant# 
root@hassio:/resin-data/homeassistant# 
root@hassio:/resin-data/homeassistant# 
root@hassio:/resin-data/homeassistant# 
root@hassio:/resin-data/homeassistant# ls
README.md	  configuration.yaml  deps	   home-assistant.log	 homebridge	     misc	  scripts.yaml	sensor	 switch  verisure.yaml
automations.yaml  customize.yaml      groups.yaml  home-assistant_v2.db  known_devices.yaml  rfxtrx.yaml  secrets.yaml	service  tts	 zigbee.db
root@hassio:/resin-data/homeassistant# cat configuration.yaml 
homeassistant:
  # Name of the location where Home Assistant is running
  name: Skumparp
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enable System Health
system_health:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

logger:
  default: error
#  logs:
#    homeassistant.components.zha: debug
#    zigpy_deconz.zigbee: debug
#    zigpy_deconz: debug

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.date
      - sensor.yr_symbol

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate

stream:

# Octopi
octoprint:
  host: !secret octopi_host
  api_key: !secret octopi_api_key
  bed: true
  number_of_tools: 1

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret octopi_still_image_url
    mjpeg_url: !secret octopi_mjpeg_url

# Google Assistant
google_assistant: !include service/google_assistant.yaml

# Notification
notify: !include service/notify.yaml

# Verisure
verisure: !include verisure.yaml

# Mercedes
#mercedesme:
#  username: !secret mercedesme_username
#  password: !secret mercedesme_password
  
# RFXtrx
rfxtrx: !include rfxtrx.yaml

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

# Entities

binary_sensor:
  - platform: workday
    country: DK
    workdays: [mon, tue, wed, thu, fri]

switch: !include_dir_merge_list switch

sensor: !include_dir_merge_list sensor

input_select: !include misc/input_select.yaml

input_boolean: !include misc/input_boolean.yaml
