homeassistant:
  # Name of the location where Home Assistant is running
  name: Skumparp
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml 

# https://www.home-assistant.io/integrations/default_config 
default_config: 

http:
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  login_attempts_threshold: 5

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

logger:
  default: error
#  logs:
#    homeassistant.components.zha: debug
#    zigpy_deconz.zigbee: debug
#    zigpy_deconz: debug

# View all events in a logbook
#logbook:
#  exclude:
#    entities:
#      - sensor.since_last_boot
#      - sensor.date
#      - sensor.yr_symbol

# Text to speech
tts:
  - platform: google_translate

stream:

# Octopi
octoprint:
  host: !secret octopi_host
  api_key: !secret octopi_api_key
  bed: true
  number_of_tools: 1

rest_command:
  shut_down_octoprint:
    url: !secret octopi_shutdown_url
    method: POST
    headers:
      X-Api-Key: !secret octopi_api_key

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret octopi_still_image_url
    mjpeg_url: !secret octopi_mjpeg_url

# Google Assistant
google_assistant: !include service/google_assistant.yaml

# Notification
notify: !include service/notify.yaml

# Verisure
verisure: !include verisure.yaml

# RFXtrx
rfxtrx: !include rfxtrx.yaml

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

# Entities

binary_sensor:
  - platform: workday
    country: DK
    workdays: [mon, tue, wed, thu, fri]

switch: !include_dir_merge_list switch

sensor: !include_dir_merge_list sensor

input_select: !include misc/input_select.yaml

input_boolean: !include misc/input_boolean.yaml
