- id: '1643563522914'
  alias: Disarm Alarm when lock is unlocked
  description: ''
  trigger:
  - platform: device
    device_id: 4c905d6f26185b312bb770039ff79099
    domain: lock
    entity_id: lock.hoveddor
    type: unlocked
  condition:
  - condition: or
    conditions:
    - condition: device
      device_id: 1c9b4a2a72fa7d149991f732bbddc260
      domain: alarm_control_panel
      entity_id: alarm_control_panel.verisure_alarm
      type: is_armed_away
    - condition: device
      device_id: 1c9b4a2a72fa7d149991f732bbddc260
      domain: alarm_control_panel
      entity_id: alarm_control_panel.verisure_alarm
      type: is_armed_home
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      device_id: 1c9b4a2a72fa7d149991f732bbddc260
    data:
      code: !secret verisure_pin
  mode: single
