# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      run: yamllint -d relaxed -f standard .
  
  check-config:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Decode secrets.yaml
      env:
        SECRETS_PROPERTIES: ${{ secrets.SECRETS_YAML }}
        SECRETS_FULLCHAIN: ${{ secrets.FULLCHAIN_PEM }}
        SECRETS_PRIVKEY: ${{ secrets.PRIVKEY_PEM }}
      run: |
        echo "$SECRETS_PROPERTIES" | base64 -d > ./secrets.yaml
        mkdir ./ssl
        echo "$SECRETS_FULLCHAIN" | base64 -d > ./ssl/fullchain.pem
        echo "$PRIVKEY_PEM" | base64 -d > ./ssl/privkey.pem

    # Runs a set of commands using the runners shell
    - name: Start Hassio and check config
      run: |
        docker run -d --name="home-assistant" -v $GITHUB_WORKSPACE:/config --net=host homeassistant/home-assistant:stable
        docker exec home-assistant python -m homeassistant --script check_config --config /config
