name: Yaml Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v2
      with:
        file_or_dir: ./*.yaml
  lintAllThingsYaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      id: yamllint
      uses: jacobtomlinson/gha-lint-yaml@master
    - name: Check outputs
      run: |
        echo "There were ${{ steps.yamllint.outputs.warnings }} YAML linting warnings." 
